### ISSUE TITLE
host the page online for free

### ISSUE THREAD

**Issue by radekstepan** [BarboraDoslikova/blood-type#2]
https://pages.github.com/

**Comment by BarboraDoslikova** [comment]
Done here: http://barboradoslikova.github.io/blood-type/

Or did you means have the actual design online like I have done for http://www.barboradoslikova.com/ ?

**Comment by radekstepan** [comment]
What I meant is:

1. have your own barboradoslikova.com domain, done
1. now for each one of your projects, set the default branch to `gh-pages` on github and work there
1. and now you will have all your projects live, so say `project1` is now visible on `barboradoslikova.com/project1`

**Comment by radekstepan** [comment]
Very cool!
